### ISSUE TITLE
Invalid Syntax!!

### ISSUE THREAD

**Issue by abutizi** [ScriptSmith/insta-scrape#2]
Hi, thanks for sharing your code. However, when I run it, I get Invalid Syntax at the 4th line 'links='

```
import requests
import json
from bs4 import BeautifulSoup
links =
```
What am I doing wrong? Is it possible to modify the code so that it automatically scrapes the total number of likes from the top 9 posts, possibly from a link with a tag?

**Comment by ScriptSmith** [comment]
Can you post the specific exception traceback?

It's likely that there are some `null`s at the end of the array you copy in, which are understood by JavaScript but not Python, so you have to just get rid of them manually

Re your second question: 

This code is very hacky and not really intended to be used as a stable library / package, just as a demonstration of how you can scrape things from Instagram in Python. In about a month's time, this functionality will be added to my project [socialreaper](https://github.com/ScriptSmith/socialreaper) and then to [reaper](https://github.com/ScriptSmith/reaper) so if it is not immediately obvious to you how to calculate the total number of likes for the top 9 posts, I'd recommend using Reaper in a month or so (I'll update this repo when it's complete). It'll let you can scrape things easily to a CSV file which you can manipulate with a spreadsheet viewer.

**Comment by abutizi** [comment]
How do I find the exception traceback? Sorry, but I'm new to python. 
When I paste your both of your JS codes into my browser, the command line spits out 'undefined' for both of them.

That will be very awesome, I will look forward to it!

**Comment by Haydardi** [comment]
How do I find the exception traceback? Sorry, but I'm new to python. 
When I paste your both of your JS codes into my browser, the command line spits out 'undefined' for both of them.

That will be very awesome, I will look forward to it!

**Comment by ScriptSmith** [comment]
Sorry, if there's syntax error there won't be an exception traceback. What I mean is can you show me exactly what Python says when you try to run the code. Like so:

```
  File "example.py", line 4
    links =
          ^
SyntaxError: invalid syntax
```

Also, it's normal for your JS console to say `undefined` because neither piece of code returns any value.

Were you able to get the JS code to successfully run, open the new tab with the list of urls, paste it into the Python file, and delete the `null`s at then end of the list?
