### ISSUE TITLE
problem with getting links

### ISSUE THREAD

**Issue by Snowbell64** [ScriptSmith/insta-scrape#3]
Hi there...! can you help me by giving more information about the link array?? I run the first part of the code in console, It just scrolls end to top over and over again (no limit just goes on) and nothing happens (or does but I couldn't figure out how to access the links and copy them into python piece). My goal is to extract the mata data of #versace for top 5000 uploaded pictures.

**Comment by larissalong** [comment]
I also wonder how long it will take to complete page scrolling and get prompts and popups. I set image count = 1000. Half an hour is gone and nothing popped up.

**Comment by ScriptSmith** [comment]
Please note that this repository is not maintained and was intended to merely show the application of a technique.

Instagram has changed a little in the past year, so things work a little differently. The way the js would look at the moment is something like this:


```javascript
var pictureCount = 100

var intervalID = window.setInterval(function() {
    var divs = document.getElementsByClassName("v1Nh3 kIKUG _bz0w")
    console.log('Page contains ' + divs.length + ' posts')
    if(divs.length < pictureCount){
        window.scrollTo(0,document.body.scrollHeight);

        setTimeout(function(){
                        window.scrollTo(0,0);
                    },250);
    } else {
        clearInterval(intervalID);
        alert("Finished!")
        if (confirm("Export data")){
            var links = []
            divs.forEach(x => links.push(x.getElementsByTagName('a')[0].href))
            window.open("data:text/json;charset=utf-8," + JSON.stringify(links))
        }
    }


}, 1000);
```

The issue is, Instagram now deletes posts from the document body once you scroll past them, so that only 36 are actually available at a given time (hence why the script never terminates). You'd need to modify this script to keep track of past posts as they are deleted

**Comment by larissalong** [comment]
Is there any idea how to modify the script in order to get all posts with a given hashtag? 
I tried your code on the below link and got error message "Failed to load". It just scrolled end to top over and over again.

https://www.instagram.com/explore/tags/sdgetaway/

**Comment by ScriptSmith** [comment]
This solution isn't efficient as you you increase pictureCount, but it works:

```javascript
var pictureCount = 1000
var links = new Set()

var intervalID = window.setInterval(function() {
    var divs = Array.from(document.getElementsByClassName("v1Nh3 kIKUG _bz0w"));
    console.log('Page contains ' + links.size + ' posts');

    divs.map(x => links.add(x.getElementsByTagName('a')[0].href));
    if(links.size < pictureCount){
        window.scrollTo(0, document.body.scrollHeight);
        setTimeout(() => window.scrollTo(0, document.body.scrollHeight - 200), 250);
    } else {
        clearInterval(intervalID);
        alert("Finished!");
        if (confirm("Export data")){
            var a = document.createElement("a");
            document.body.appendChild(a);

            var file = new Blob([JSON.stringify(Array.from(links))], {type: "octet/stream"});
            var url = window.URL.createObjectURL(file);

            a.href = url
            a.download = 'data.json';
            a.click();

            window.URL.revokeObjectURL(url)
        }
    }
}, 1000);
```

**Comment by larissalong** [comment]
@ScriptSmith It took me 4 hours to get the json file with 100 post links on a given hashtag page. This may not be efficient as you mentioned, but thank you all the same for the great help!

**Comment by ScriptSmith** [comment]
It shouldn't take that long to load only 100 posts, but as you move into the thousands I imagine it will be quite slow.

I'm not interested in providing a more efficient solution, but it would not be difficult for someone with non-trivial javascript skills to write. You basically need to write an algorithm to figure out which posts have already been loaded and added to `links`.

**Comment by larissalong** [comment]
@ScriptSmith Thank you!

**Comment by ScriptSmith** [comment]
Just a note that my current project [Instamancer](https://github.com/ScriptSmith/instamancer) is a suitable replacement for this code.
